# Generated by Django 3.2.3 on 2021-08-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user.png', upload_to='static/images'),
        ),
    ]
